image: python:3.13

cache:
    paths:
      - .cache/pip

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - test
  - deploy

before_script:
  - pip install -U -e .

build:
  stage: build
  script:
    - pip install build
    - python -m build
  artifacts:
    name: tibiawikisql-dist
    paths:
      - dist/

docs:
  stage: build
  script:
    - pip install -U -e .[docs]
    - mkdocs build
  artifacts:
    name: tibiawikisql-docs
    paths:
      - site/

coverage:
  stage: test
  script:
      - pip install coverage
      - coverage run setup.py test
      - coverage report
      - coverage html
      - coverage xml
  artifacts:
    name: Coverage_Report
    paths:
      - htmlcov/
      - coverage.xml

database:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
  script:
    - tibiawikisql generate
  cache:
    paths:
      - images/
  artifacts:
    paths:
    - tibiawiki.db


pages:
  stage: deploy
  dependencies:
    - docs
    - coverage
  script:
    - mkdir public
    - mv htmlcov/ public/coverage/
    - mv site/* public/
  artifacts:
    paths:
      - public
  only:
    - main
    - dev
