name: 🗄 Build Database
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00

jobs:
  build:
    name: ⚙️ Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚚
        uses: actions/checkout@v7

      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install ⚙️
        run:  pip install -U -e .

      - name: Cache Images 📦
        uses: actions/cache@v6
        with:
          path: images/
          key: images
          restore-keys: |
            images

      - name: Generate Database 🗄
        run: tibiawikisql generate --skip-deprecated

      - name: Upload database 🚀
        uses: actions/upload-artifact@v6
        with:
          name: tibiawiki-db
          path: |
            tibiawiki.db
            images/
