name: 🐙 Github Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 📄 Build & Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚚
        uses: actions/checkout@v7

      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies ⚙️
        run: |
          pip install -U -e .[docs]

      - name: Build MkDocs 📙
        run: |
          mkdocs build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
